import os
import re
import time
import uuid
import threading
import glob
import requests
import telebot
import yt_dlp
import internetarchive as ia
from http.server import HTTPServer, BaseHTTPRequestHandler

# --- CREDENTIALS ---
TELEGRAM_TOKEN = "8644006980:AAEKBACweZ9kg4M482anjYUkEP5O7DZF7wQ"
IA_ACCESS = "SjzCWtMdMVYsRBXl"
IA_SECRET = "THTnm9iXNVafYy9b"

bot = telebot.TeleBot(TELEGRAM_TOKEN, threaded=False)

# --- LIVE WEB LOG CONSOLE ---
logs_history = []

def add_log(msg):
    timestamp = time.strftime("%H:%M:%S")
    entry = f"[{timestamp}] {msg}"
    print(entry)
    logs_history.append(entry)
    if len(logs_history) > 60:
        logs_history.pop(0)

class DashboardHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-type", "text/html; charset=utf-8")
        self.end_headers()
        
        log_rows = "".join([f"<div class='log-row'>{log}</div>" for log in reversed(logs_history)]) or "<div class='log-row'>No activity recorded yet...</div>"
        
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <title>Universal Archive Uploader</title>
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <meta http-equiv="refresh" content="3">
            <style>
                body {{ background: #0b0f19; color: #e2e8f0; font-family: monospace; padding: 20px; margin: 0; }}
                .container {{ max-width: 850px; margin: 0 auto; }}
                .header {{ background: #1e293b; padding: 15px 20px; border-radius: 10px; display: flex; justify-content: space-between; align-items: center; border-left: 5px solid #10b981; }}
                .badge {{ background: #059669; color: white; padding: 6px 12px; border-radius: 20px; font-weight: bold; font-size: 0.8rem; }}
                .box {{ background: #111827; border: 1px solid #1f2937; border-radius: 10px; padding: 20px; margin-top: 15px; }}
                .console {{ background: #030712; padding: 15px; border-radius: 8px; height: 350px; overflow-y: auto; color: #38bdf8; border: 1px solid #374151; font-size: 0.85rem; line-height: 1.6; }}
                .log-row {{ border-bottom: 1px solid #1f2937; padding: 4px 0; word-break: break-all; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h2>🚀 Universal Archive Uploader</h2>
                    <span class="badge">● ONLINE (Auto-refresh 3s)</span>
                </div>
                <div class="box">
                    <h3>Live System & Upload Logs</h3>
                    <div class="console">{log_rows}</div>
                </div>
            </div>
        </body>
        </html>
        """
        self.wfile.write(html.encode("utf-8"))

    def log_message(self, format, *args):
        return

def run_web():
    port = int(os.environ.get("PORT", 8080))
    server = HTTPServer(("0.0.0.0", port), DashboardHandler)
    server.serve_forever()

def format_size(bytes_size):
    for unit in ['B', 'KB', 'MB', 'GB']:
        if bytes_size < 1024:
            return f"{bytes_size:.2f} {unit}"
        bytes_size /= 1024
    return f"{bytes_size:.2f} TB"

# --- COMMANDS ---
@bot.message_handler(commands=["start", "help"])
def send_welcome(message):
    add_log(f"Chat {message.chat.id} sent /start")
    bot.reply_to(
        message,
        "👋 **Universal Archive Uploader Bot**\n\n"
        "⚡ **Supported Inputs:**\n"
        "• YouTube, Instagram, Facebook, TikTok links\n"
        "• Direct Video/File Stream URLs\n"
        "• Direct Bot Download Links\n\n"
        "Simply send any URL, and the bot will automatically process, extract, and upload it to Internet Archive.",
        parse_mode="Markdown"
    )

# --- DIRECT LINKS & YT-DLP HANDLER ---
@bot.message_handler(func=lambda msg: True)
def handle_universal_url(message):
    text = message.text.strip()
    url_match = re.search(r'(https?://[^\s]+)', text)
    
    if not url_match:
        bot.reply_to(message, "⚠️ Please send a valid link (YouTube, stream URL, or direct media link).")
        return

    url = url_match.group(0)

    if "t.me/" in url and not ("t.me/c/" in url or "t.me/b/" in url):
        bot.reply_to(message, "⚠️ For Telegram files, paste the direct stream link generated by a file-to-link service.")
        return

    add_log(f"Received URL to process: {url}")
    status = bot.reply_to(message, "⚡ **Analyzing link & fetching metadata...**", parse_mode="Markdown")
    
    item_id = f"auto_{uuid.uuid4().hex[:8]}"
    output_template = f"/tmp/{item_id}.%(ext)s"
    
    last_update = [time.time()]

    # Progress hook for yt-dlp
    def ytdl_hook(d):
        if d['status'] == 'downloading':
            now = time.time()
            if now - last_update[0] >= 3:
                last_update[0] = now
                downloaded = d.get('downloaded_bytes', 0)
                total = d.get('total_bytes') or d.get('total_bytes_estimate') or 0
                speed = d.get('speed') or 0
                eta = d.get('eta') or 0

                if total > 0:
                    pct = (downloaded / total) * 100
                    filled = int(pct / 10)
                    bar = "■" * filled + "□" * (10 - filled)
                    text_prog = (
                        f"📥 **Downloading Media...**\n\n"
                        f"`[{bar}]` **{pct:.1f}%**\n\n"
                        f"⚡ **Speed:** `{format_size(speed)}/s`\n"
                        f"📁 **Size:** `{format_size(downloaded)}` / `{format_size(total)}`\n"
                        f"⏳ **ETA:** `{eta}s`"
                    )
                else:
                    text_prog = f"📥 **Downloading Stream...**\n\n⚡ **Speed:** `{format_size(speed)}/s`\n📁 **Downloaded:** `{format_size(downloaded)}`"
                
                try:
                    bot.edit_message_text(text_prog, chat_id=message.chat.id, message_id=status.message_id, parse_mode="Markdown")
                except Exception:
                    pass

    ydl_opts = {
        'outtmpl': output_template,
        'format': 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best',
        'progress_hooks': [ytdl_hook],
        'quiet': True,
        'no_warnings': True
    }

    try:
        # 1. Attempt download using yt-dlp (YouTube, Social Media, Direct Streams)
        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(url, download=True)
                title = info.get('title', f"Upload {item_id}")
        except Exception:
            # 2. Fallback to direct chunked streaming for pure binary file links
            add_log(f"Falling back to direct stream downloader for: {url}")
            file_path = f"/tmp/{item_id}.mp4"
            title = f"Stream Upload {item_id}"
            
            with requests.get(url, stream=True, timeout=60) as r:
                r.raise_for_status()
                with open(file_path, "wb") as f:
                    for chunk in r.iter_content(chunk_size=1024 * 1024):
                        if chunk:
                            f.write(chunk)

        # Locate downloaded file
        matching_files = glob.glob(f"/tmp/{item_id}.*")
        if not matching_files:
            raise Exception("File failed to download or save.")

        downloaded_file_path = matching_files[0]
        file_size = os.path.getsize(downloaded_file_path)

        add_log(f"Download complete ({format_size(file_size)}). Uploading {item_id} to Internet Archive...")
        bot.edit_message_text("🚀 **Uploading to Internet Archive... Please wait.**", chat_id=message.chat.id, message_id=status.message_id, parse_mode="Markdown")

        # Upload to Internet Archive
        item = ia.get_item(item_id)
        item.upload(
            downloaded_file_path,
            metadata={"title": title, "mediatype": "movies"},
            access_key=IA_ACCESS,
            secret_key=IA_SECRET
        )

        archive_url = f"https://archive.org/details/{item_id}"
        add_log(f"Upload Complete: {archive_url}")

        bot.edit_message_text(
            f"✅ **Upload Complete!**\n\n"
            f"🎬 **Title:** `{title}`\n"
            f"📦 **Size:** `{format_size(file_size)}`\n"
            f"🔗 **Archive Link:** {archive_url}",
            chat_id=message.chat.id,
            message_id=status.message_id,
            parse_mode="Markdown"
        )

    except Exception as e:
        add_log(f"Process Error: {str(e)}")
        bot.edit_message_text(f"❌ **Error:** {str(e)}", chat_id=message.chat.id, message_id=status.message_id)

    finally:
        for f in glob.glob(f"/tmp/{item_id}.*"):
            if os.path.exists(f):
                os.remove(f)

if __name__ == "__main__":
    t = threading.Thread(target=run_web, daemon=True)
    t.start()

    try:
        bot.remove_webhook()
        time.sleep(1)
    except Exception:
        pass

    add_log("Bot online. Multi-source universal downloader running...")
    bot.infinity_polling(skip_pending=True)
